version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17.6
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  test:
    docker:
      - image: circleci/node:14.17.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
            - node-v1-
      - run: npm install
      - run: npm run test
      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'
# workflows:
#   build-and-deploy:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
#       - deploy:
#           requires:
#             - test
#           filters:
#             branches:
#               only: main
